<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="madhu" ignored="0" name="Sanity" tests="7" failures="1" timestamp="21 Jul 2018 08:39:06 GMT" time="0.124" errors="0">
  <testcase name="demo" time="0.025" classname="testng.TestNG_2"/>
  <testcase name="WebLoginCarLoan" time="0.022" classname="testng.TestNG_3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.TestNG_3.WebLoginCarLoan(TestNG_3.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- WebLoginCarLoan -->
  <testcase name="NewCarLoan" time="0.004" classname="testng.TestNG_3"/>
  <testcase name="demo2" time="0.015" classname="testng.TestNG_2"/>
  <testcase name="NewCarLoan" time="0.003" classname="testng.TestNG_3"/>
  <testcase name="NewCarLoan" time="0.006" classname="testng.TestNG_3"/>
  <testcase name="MobileLoginCarLoan" time="0.0" classname="testng.TestNG_3">
    <skipped/>
  </testcase> <!-- MobileLoginCarLoan -->
</testsuite> <!-- Sanity -->
